### ISSUE TITLE
Compilation time

### ISSUE THREAD

**Issue by gudovskiy** [leo2105/Caffe-installation-Raspberry-Pi-3#2]
Hi, just curious how long does it take to execute "make all" on your PI?

**Comment by leo2105** [comment]
I don't remember, I guess 2 or 3 hours. it takes lees time if you write make all -j(#cores_of_your_pc)

**Comment by gudovskiy** [comment]
@leo2105 thanks, will compare with my result. Currently my compilation is stuck at _caffe.cpp src for few hours and I use single core.

**Comment by gudovskiy** [comment]
@leo2105 my problem was that compilation with python interface caused system out of memory. Switching to terminal only boot helped to release some memory.
